### ISSUE TITLE
Support websocket events

### ISSUE THREAD

**Issue by AdaptingAFM** [SocketSomeone/necord#135]
### Feature

Hey! Currently NecordEvents has quite a lot of events that are really helpful, but most of ws-events are missing, and they are really useful for debugging and other stuff.

### Ideal solution or implementation

Allow the @On decorator to handle the missing ws-events.

**Comment by AdaptingAFM** [comment]
As these are only useful for debugging, I doubt they should be accessible within the @On decorator. NecordEvents are meant for the events of the client, not for the websocket. If someone needs to debug, they should just access the DiscordJS client.

**Comment by AdaptingAFM** [comment]
Actually, this is a kind of a need. There are no current ways of listening for websockets events alike 'RESUMED' at the current state of the framework.

**Comment by SocketSomeone** [comment]
Hi, @AdaptingAFM, 

It seems to me that this feature is only useful for debugging. 
But for now I am not busy with other tasks, so you can develop this module yourself. I will not close the Issue if this feature is needed by a large number of people - I will do it.

Thanks for your feature request!
