### ISSUE TITLE
Ordering command arguments

### ISSUE THREAD

**Issue by AntonyGarand** [SocketSomeone/necord#194]
### Feature

Slash command arguments are currently sorted in the order they are in the class, and can't be reordered within necord.

I'd recommend to have an `index: number` property added to the various command options (`StringOption`, `BooleanOption`, etc.) to specify the order in which we want them to appear.

![image](https://user-images.githubusercontent.com/9059487/163451250-74d3f93b-7c1f-4d83-91c1-2009e62351f6.png)

### Ideal solution or implementation

Adding an `index` property on the various comand options:
```ts
  @StringOption({
    name: "option",
    description:
      "The rsn for one of your accounts (defaults to all accounts if no rsn is provided)",
    required: false,
    autocomplete: true,
    index: 2,
  })
```

**Comment by SocketSomeone** [comment]
Closed by https://github.com/SocketSomeone/necord/commit/8ffa69cb256c68e35e927220ec53877218dae164.
Wait `5.0.0`
