### ISSUE TITLE
Development mode - Set all commands to a specific  guild

### ISSUE THREAD

**Issue by AntonyGarand** [SocketSomeone/necord#85]
### Feature

As guild commands and global commands have a different timeout, the global ones being cached for up to an hour, development is best done with guild commands when possible.
For this purpose, I suggest a way to pass a development guild id to necord, which would do the same as adding the `@Guilds` decorator on all commands, applying it globally.

### Ideal solution or implementation

I believe this would be best applied within the necord module configuration:

```typescript
    NecordModule.forRoot({
      token: "token",
      intents: [],
      isDevelopment: false | "guild" | "guilds"[]
    }),
```

**Comment by SocketSomeone** [comment]
Hey, thanks for your request!
I'll do it in the next minor version! 

I correctly understood that "guild" is Snowflake type?
isDevelopment: `false` | `Snowflake` | `Snowflake[]`

**Comment by AntonyGarand** [comment]
This is what would feel most natural to me, but equivalent solutions might work as well

**Comment by SocketSomeone** [comment]
Added in v4.1.0
