### ISSUE TITLE
Autocomplete: Support multiple `@Autocomplete` on a single command

### ISSUE THREAD

**Issue by AntonyGarand** [SocketSomeone/necord#94]
### Feature

Add support for multiple `@Autocomplete` on a single command.
At the moment, to support multiple autocomplete fields, one must add this feature within the autocompleter itself, by using `focused.name` to find out which component it needs to autocomplete.
```ts
switch(focused.name) {
  case 'color':
    ...
  case 'meal'
    ...
  default:
    []
}
```

This makes it hard to reuse the same autocomplete logic across components: If many commands rely on the colorAutocomplete, but only one of them needs to also autocomplete the meal, you would need to manually merge both of them for this one command.

### Ideal solution or implementation

I would like to add support for autocomplete chaining: 
```ts
@Autocomplete(colorAutocomplete, mealAutocomplete)
```
This would run all of the autocompletes until one returns data, allowing them to return a falsy value if the autocomplete is not made for this input.

This would also open the way for a Global autocomplete, filtering itself from of the input.name, to reduce boilerplate:
```ts
NecordModule.forRoot({
  // ...
  globalAutocomplete: [ colorAutocomplete ]
}),
```

**Comment by SocketSomeone** [comment]
Implemented in 4.2.1👀
