### ISSUE TITLE
Support native guards

### ISSUE THREAD

**Issue by AntonyGarand** [SocketSomeone/necord#95]
### Feature

When doing server management feature, such as changing the prefix or whitelisted channels, the command must be restricted to elevated users.
Instead of making a custom guard or decorator, I believe this would be a good feature to integrate within necord itself.

Currently, this must be done in a guard, and using a "manual" way to specify the required permissions.
Ex:
```ts
// command
@UseGuards(ServerAdminGuard)
// guard
interaction.memberPermissions.has(Permissions.FLAGS.MANAGE_GUILD)
```

It would be much cleaner to have this within its own `@GuildPermission` decorator, or within arguments to the Command decorator.

### Ideal solution or implementation

```ts
@SlashCommand('name', 'desc', { defaultPermission: true, guildPermission: [Permissions.FLAGS.MANAGE_GUILD] } )
// or
@SlashCommand('name','desc')
@GuildPermissions(Permissions.FLAGS.MANAGE_GUILD)
```

**Comment by SocketSomeone** [comment]
`GuildPermission` will check bot permissions or member?

**Comment by AntonyGarand** [comment]
member permission in guild context

**Comment by SocketSomeone** [comment]
Ok, native guards:

- [ ] Enabled
- [ ] Cooldown
- [ ] GuildPermissions
- [ ] UserPermissions
- [ ] RolePermissions
- [ ] NSFW
- [ ] ChannelOnly
- [ ] OwnerOnly & GuildOwnerOnly
- [ ] GuildOnly & DmOnly

Anything else?

**Comment by AntonyGarand** [comment]
- [ ] ThreadOnly
- [ ] TextChannelOnly / ChannelTypeOnly(type) - Ex for announcement channels
Otherwise looks pretty complete!
