### ISSUE TITLE
Guards: Provide event handler context

### ISSUE THREAD

**Issue by AntonyGarand** [SocketSomeone/necord#97]
### Feature

When an event is captured by multiple event handlers, such as by having a `@On('interactionCreate')` decorator, a new context will be created and sent to the various receiving parties.
While this is not bad or wrong it itself, it can cause an issue with global guards: If your guard replies or interacts to the interaction, as the guard will be executed multiple times, it can cause the message to be sent multiple times, or the second+ guard to trigger a discord error "Unknown interaction".
Note that even in the following code, as both interactions are technically a new context, `interaction.replied` is false in both of them.
![image](https://user-images.githubusercontent.com/9059487/151644894-aac0d2ce-f89f-4e52-bff2-c2e50261e19b.png)

### Ideal solution or implementation

1. Provide the execution context within `NecordExecutionContext.getInfo()`, with the entity on which the decorator is applied.
This will allow us to avoid answering or replying to the guard if the execution is not on an ApplicationCommand, but on the generic InteractionCreate handler instead for example.
2. Provide the same discord context within the different components: The interaction itself should be shared, making it so `interaction.replied` is properly populated.
3. Provide the index of the interaction within the necord context, so we know to only block it once for example.

**Comment by SocketSomeone** [comment]
Fixed by 4.2.0
